# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_account_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.IDC'),
        ),
    ]
